default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] || "tibiajs_development" %>
  username: <%= ENV['DB_USER'] || "postgres" %>
  password: <%= ENV['DB_PASS'] || "" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  pool: <%= ENV['DB_POOL'] || 15 %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  idle_timeout: <%= ENV['DB_IDLE_TIMEOUT'] || 300 %>
  checkout_timeout: <%= ENV['DB_CHECKOUT_TIMEOUT'] || 5 %>
  reaping_frequency: <%= ENV['DB_REAPING_FREQUENCY'] || 30 %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  
test:
  <<: *default
  database: tibiajs_test

production:
  <<: *default
